name: Docker Build

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: v1.31
      run: docker build ./1.31
    - name: v1.32
      run: docker build ./1.32
    - name: v1.33
      run: docker build ./1.33
